// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: proto/cluster/event.proto

package eventpb

import (
	commpb "github.com/ict/tide/proto/commpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StubMode int32

const (
	StubMode_ENTRY StubMode = 0
	StubMode_FN    StubMode = 1
)

// Enum value maps for StubMode.
var (
	StubMode_name = map[int32]string{
		0: "ENTRY",
		1: "FN",
	}
	StubMode_value = map[string]int32{
		"ENTRY": 0,
		"FN":    1,
	}
)

func (x StubMode) Enum() *StubMode {
	p := new(StubMode)
	*p = x
	return p
}

func (x StubMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StubMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_event_proto_enumTypes[0].Descriptor()
}

func (StubMode) Type() protoreflect.EnumType {
	return &file_proto_cluster_event_proto_enumTypes[0]
}

func (x StubMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StubMode.Descriptor instead.
func (StubMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{0}
}

type RoutineDoneEvent_Status int32

const (
	RoutineDoneEvent_SUCC RoutineDoneEvent_Status = 0
	RoutineDoneEvent_FAIL RoutineDoneEvent_Status = 1
)

// Enum value maps for RoutineDoneEvent_Status.
var (
	RoutineDoneEvent_Status_name = map[int32]string{
		0: "SUCC",
		1: "FAIL",
	}
	RoutineDoneEvent_Status_value = map[string]int32{
		"SUCC": 0,
		"FAIL": 1,
	}
)

func (x RoutineDoneEvent_Status) Enum() *RoutineDoneEvent_Status {
	p := new(RoutineDoneEvent_Status)
	*p = x
	return p
}

func (x RoutineDoneEvent_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutineDoneEvent_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_event_proto_enumTypes[1].Descriptor()
}

func (RoutineDoneEvent_Status) Type() protoreflect.EnumType {
	return &file_proto_cluster_event_proto_enumTypes[1]
}

func (x RoutineDoneEvent_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutineDoneEvent_Status.Descriptor instead.
func (RoutineDoneEvent_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{14, 0}
}

type EventList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *EventList) Reset() {
	*x = EventList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Event) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type EventResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{2}
}

type StubCreateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId      string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ImageName  string   `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Commands   []string `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	Mode       StubMode `protobuf:"varint,4,opt,name=mode,proto3,enum=cluster.StubMode" json:"mode,omitempty"`
	VolumePair string   `protobuf:"bytes,5,opt,name=volume_pair,json=volumePair,proto3" json:"volume_pair,omitempty"`
}

func (x *StubCreateEvent) Reset() {
	*x = StubCreateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StubCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubCreateEvent) ProtoMessage() {}

func (x *StubCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubCreateEvent.ProtoReflect.Descriptor instead.
func (*StubCreateEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{3}
}

func (x *StubCreateEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StubCreateEvent) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *StubCreateEvent) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *StubCreateEvent) GetMode() StubMode {
	if x != nil {
		return x.Mode
	}
	return StubMode_ENTRY
}

func (x *StubCreateEvent) GetVolumePair() string {
	if x != nil {
		return x.VolumePair
	}
	return ""
}

type StubStopEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StubId string `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
}

func (x *StubStopEvent) Reset() {
	*x = StubStopEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StubStopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubStopEvent) ProtoMessage() {}

func (x *StubStopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubStopEvent.ProtoReflect.Descriptor instead.
func (*StubStopEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{4}
}

func (x *StubStopEvent) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

type AppStopEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *AppStopEvent) Reset() {
	*x = AppStopEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppStopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStopEvent) ProtoMessage() {}

func (x *AppStopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStopEvent.ProtoReflect.Descriptor instead.
func (*AppStopEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{5}
}

func (x *AppStopEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type NodeSyncEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainResource *commpb.Resource `protobuf:"bytes,3,opt,name=remain_resource,json=remainResource,proto3" json:"remain_resource,omitempty"`
}

func (x *NodeSyncEvent) Reset() {
	*x = NodeSyncEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSyncEvent) ProtoMessage() {}

func (x *NodeSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSyncEvent.ProtoReflect.Descriptor instead.
func (*NodeSyncEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{6}
}

func (x *NodeSyncEvent) GetRemainResource() *commpb.Resource {
	if x != nil {
		return x.RemainResource
	}
	return nil
}

type NodeNewEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId        string           `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          int32            `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	TotalResource *commpb.Resource `protobuf:"bytes,4,opt,name=total_resource,json=totalResource,proto3" json:"total_resource,omitempty"`
	AppList       []string         `protobuf:"bytes,5,rep,name=app_list,json=appList,proto3" json:"app_list,omitempty"`
	IsReply       bool             `protobuf:"varint,6,opt,name=is_reply,json=isReply,proto3" json:"is_reply,omitempty"`
}

func (x *NodeNewEvent) Reset() {
	*x = NodeNewEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeNewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeNewEvent) ProtoMessage() {}

func (x *NodeNewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeNewEvent.ProtoReflect.Descriptor instead.
func (*NodeNewEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{7}
}

func (x *NodeNewEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeNewEvent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeNewEvent) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *NodeNewEvent) GetTotalResource() *commpb.Resource {
	if x != nil {
		return x.TotalResource
	}
	return nil
}

func (x *NodeNewEvent) GetAppList() []string {
	if x != nil {
		return x.AppList
	}
	return nil
}

func (x *NodeNewEvent) GetIsReply() bool {
	if x != nil {
		return x.IsReply
	}
	return false
}

type StubSyncEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StubId      string `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	EstWaitTime uint64 `protobuf:"varint,2,opt,name=est_wait_time,json=estWaitTime,proto3" json:"est_wait_time,omitempty"`
	UpdateTime  int64  `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *StubSyncEvent) Reset() {
	*x = StubSyncEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StubSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubSyncEvent) ProtoMessage() {}

func (x *StubSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubSyncEvent.ProtoReflect.Descriptor instead.
func (*StubSyncEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{8}
}

func (x *StubSyncEvent) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *StubSyncEvent) GetEstWaitTime() uint64 {
	if x != nil {
		return x.EstWaitTime
	}
	return 0
}

func (x *StubSyncEvent) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AppNewEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ImageName string   `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Commands  []string `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *AppNewEvent) Reset() {
	*x = AppNewEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppNewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppNewEvent) ProtoMessage() {}

func (x *AppNewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppNewEvent.ProtoReflect.Descriptor instead.
func (*AppNewEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{9}
}

func (x *AppNewEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppNewEvent) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *AppNewEvent) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type StubNewEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StubId     string   `protobuf:"bytes,1,opt,name=stub_id,json=stubId,proto3" json:"stub_id,omitempty"`
	AppId      string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Mode       StubMode `protobuf:"varint,3,opt,name=mode,proto3,enum=cluster.StubMode" json:"mode,omitempty"`
	CreateTime int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *StubNewEvent) Reset() {
	*x = StubNewEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StubNewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubNewEvent) ProtoMessage() {}

func (x *StubNewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubNewEvent.ProtoReflect.Descriptor instead.
func (*StubNewEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{10}
}

func (x *StubNewEvent) GetStubId() string {
	if x != nil {
		return x.StubId
	}
	return ""
}

func (x *StubNewEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StubNewEvent) GetMode() StubMode {
	if x != nil {
		return x.Mode
	}
	return StubMode_ENTRY
}

func (x *StubNewEvent) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type RoutineSubmitEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtnId      string `protobuf:"bytes,1,opt,name=rtn_id,json=rtnId,proto3" json:"rtn_id,omitempty"`
	FnName     string `protobuf:"bytes,2,opt,name=fn_name,json=fnName,proto3" json:"fn_name,omitempty"`
	Args       []byte `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	SubmitTime int64  `protobuf:"varint,4,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	InitSid    string `protobuf:"bytes,5,opt,name=init_sid,json=initSid,proto3" json:"init_sid,omitempty"`
}

func (x *RoutineSubmitEvent) Reset() {
	*x = RoutineSubmitEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineSubmitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineSubmitEvent) ProtoMessage() {}

func (x *RoutineSubmitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineSubmitEvent.ProtoReflect.Descriptor instead.
func (*RoutineSubmitEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{11}
}

func (x *RoutineSubmitEvent) GetRtnId() string {
	if x != nil {
		return x.RtnId
	}
	return ""
}

func (x *RoutineSubmitEvent) GetFnName() string {
	if x != nil {
		return x.FnName
	}
	return ""
}

func (x *RoutineSubmitEvent) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RoutineSubmitEvent) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *RoutineSubmitEvent) GetInitSid() string {
	if x != nil {
		return x.InitSid
	}
	return ""
}

type RoutineReceiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtnId      string `protobuf:"bytes,1,opt,name=rtn_id,json=rtnId,proto3" json:"rtn_id,omitempty"`
	ReceiverId string `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // Cloud: NodeId, Edge: StubId
	ToCloud    bool   `protobuf:"varint,3,opt,name=to_cloud,json=toCloud,proto3" json:"to_cloud,omitempty"`
}

func (x *RoutineReceiveEvent) Reset() {
	*x = RoutineReceiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineReceiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineReceiveEvent) ProtoMessage() {}

func (x *RoutineReceiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineReceiveEvent.ProtoReflect.Descriptor instead.
func (*RoutineReceiveEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{12}
}

func (x *RoutineReceiveEvent) GetRtnId() string {
	if x != nil {
		return x.RtnId
	}
	return ""
}

func (x *RoutineReceiveEvent) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *RoutineReceiveEvent) GetToCloud() bool {
	if x != nil {
		return x.ToCloud
	}
	return false
}

type RoutineWaitGetEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithData bool   `protobuf:"varint,1,opt,name=with_data,json=withData,proto3" json:"with_data,omitempty"`
	RtnId    string `protobuf:"bytes,2,opt,name=rtn_id,json=rtnId,proto3" json:"rtn_id,omitempty"`
	ReqSid   string `protobuf:"bytes,3,opt,name=req_sid,json=reqSid,proto3" json:"req_sid,omitempty"`
}

func (x *RoutineWaitGetEvent) Reset() {
	*x = RoutineWaitGetEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineWaitGetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineWaitGetEvent) ProtoMessage() {}

func (x *RoutineWaitGetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineWaitGetEvent.ProtoReflect.Descriptor instead.
func (*RoutineWaitGetEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{13}
}

func (x *RoutineWaitGetEvent) GetWithData() bool {
	if x != nil {
		return x.WithData
	}
	return false
}

func (x *RoutineWaitGetEvent) GetRtnId() string {
	if x != nil {
		return x.RtnId
	}
	return ""
}

func (x *RoutineWaitGetEvent) GetReqSid() string {
	if x != nil {
		return x.ReqSid
	}
	return ""
}

type RoutineDoneEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtnId    string                  `protobuf:"bytes,1,opt,name=rtn_id,json=rtnId,proto3" json:"rtn_id,omitempty"`
	Status   RoutineDoneEvent_Status `protobuf:"varint,2,opt,name=status,proto3,enum=cluster.RoutineDoneEvent_Status" json:"status,omitempty"`
	WithData bool                    `protobuf:"varint,3,opt,name=with_data,json=withData,proto3" json:"with_data,omitempty"`
	Result   []byte                  `protobuf:"bytes,4,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Error    *string                 `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *RoutineDoneEvent) Reset() {
	*x = RoutineDoneEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cluster_event_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineDoneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineDoneEvent) ProtoMessage() {}

func (x *RoutineDoneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_event_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineDoneEvent.ProtoReflect.Descriptor instead.
func (*RoutineDoneEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_event_proto_rawDescGZIP(), []int{14}
}

func (x *RoutineDoneEvent) GetRtnId() string {
	if x != nil {
		return x.RtnId
	}
	return ""
}

func (x *RoutineDoneEvent) GetStatus() RoutineDoneEvent_Status {
	if x != nil {
		return x.Status
	}
	return RoutineDoneEvent_SUCC
}

func (x *RoutineDoneEvent) GetWithData() bool {
	if x != nil {
		return x.WithData
	}
	return false
}

func (x *RoutineDoneEvent) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RoutineDoneEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_proto_cluster_event_proto protoreflect.FileDescriptor

var file_proto_cluster_event_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x33, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x49, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0xab, 0x01, 0x0a, 0x0f, 0x53, 0x74, 0x75, 0x62, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x75, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x50, 0x61, 0x69, 0x72, 0x22, 0x28,
	0x0a, 0x0d, 0x53, 0x74, 0x75, 0x62, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x75, 0x62, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x53,
	0x74, 0x6f, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22,
	0x4a, 0x0a, 0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x39, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0e, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xc4, 0x01, 0x0a, 0x0c,
	0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0d, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x70, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x6d, 0x0a, 0x0d, 0x53, 0x74, 0x75, 0x62, 0x53, 0x79, 0x6e, 0x63, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x62, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x65, 0x73, 0x74, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x65, 0x73, 0x74, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x4e, 0x65, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x62, 0x4e, 0x65, 0x77, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x75, 0x62, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x75, 0x62,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x12,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x74, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x74, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x5f,
	0x73, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x53,
	0x69, 0x64, 0x22, 0x68, 0x0a, 0x13, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x74, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x74, 0x6e, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x6f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x22, 0x62, 0x0a, 0x13,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x57, 0x61, 0x69, 0x74, 0x47, 0x65, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x74, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x74, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x5f, 0x73,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x71, 0x53, 0x69, 0x64,
	0x22, 0xeb, 0x01, 0x0a, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x44, 0x6f, 0x6e, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x74, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x74, 0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x44, 0x6f,
	0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x22, 0x1c, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x55, 0x43, 0x43, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x1d,
	0x0a, 0x08, 0x53, 0x74, 0x75, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e,
	0x54, 0x52, 0x59, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x4e, 0x10, 0x01, 0x32, 0x45, 0x0a,
	0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a,
	0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x61, 0x6e, 0x7a, 0x73, 0x2f, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cluster_event_proto_rawDescOnce sync.Once
	file_proto_cluster_event_proto_rawDescData = file_proto_cluster_event_proto_rawDesc
)

func file_proto_cluster_event_proto_rawDescGZIP() []byte {
	file_proto_cluster_event_proto_rawDescOnce.Do(func() {
		file_proto_cluster_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cluster_event_proto_rawDescData)
	})
	return file_proto_cluster_event_proto_rawDescData
}

var file_proto_cluster_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_cluster_event_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_cluster_event_proto_goTypes = []interface{}{
	(StubMode)(0),                // 0: cluster.StubMode
	(RoutineDoneEvent_Status)(0), // 1: cluster.RoutineDoneEvent.Status
	(*EventList)(nil),            // 2: cluster.EventList
	(*Event)(nil),                // 3: cluster.Event
	(*EventResult)(nil),          // 4: cluster.EventResult
	(*StubCreateEvent)(nil),      // 5: cluster.StubCreateEvent
	(*StubStopEvent)(nil),        // 6: cluster.StubStopEvent
	(*AppStopEvent)(nil),         // 7: cluster.AppStopEvent
	(*NodeSyncEvent)(nil),        // 8: cluster.NodeSyncEvent
	(*NodeNewEvent)(nil),         // 9: cluster.NodeNewEvent
	(*StubSyncEvent)(nil),        // 10: cluster.StubSyncEvent
	(*AppNewEvent)(nil),          // 11: cluster.AppNewEvent
	(*StubNewEvent)(nil),         // 12: cluster.StubNewEvent
	(*RoutineSubmitEvent)(nil),   // 13: cluster.RoutineSubmitEvent
	(*RoutineReceiveEvent)(nil),  // 14: cluster.RoutineReceiveEvent
	(*RoutineWaitGetEvent)(nil),  // 15: cluster.RoutineWaitGetEvent
	(*RoutineDoneEvent)(nil),     // 16: cluster.RoutineDoneEvent
	(*commpb.Resource)(nil),      // 17: common.Resource
}
var file_proto_cluster_event_proto_depIdxs = []int32{
	3,  // 0: cluster.EventList.events:type_name -> cluster.Event
	0,  // 1: cluster.StubCreateEvent.mode:type_name -> cluster.StubMode
	17, // 2: cluster.NodeSyncEvent.remain_resource:type_name -> common.Resource
	17, // 3: cluster.NodeNewEvent.total_resource:type_name -> common.Resource
	0,  // 4: cluster.StubNewEvent.mode:type_name -> cluster.StubMode
	1,  // 5: cluster.RoutineDoneEvent.status:type_name -> cluster.RoutineDoneEvent.Status
	2,  // 6: cluster.EventService.SendEvent:input_type -> cluster.EventList
	4,  // 7: cluster.EventService.SendEvent:output_type -> cluster.EventResult
	7,  // [7:8] is the sub-list for method output_type
	6,  // [6:7] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_cluster_event_proto_init() }
func file_proto_cluster_event_proto_init() {
	if File_proto_cluster_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cluster_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StubCreateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StubStopEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppStopEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSyncEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeNewEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StubSyncEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppNewEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StubNewEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineSubmitEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineReceiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineWaitGetEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cluster_event_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutineDoneEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_cluster_event_proto_msgTypes[14].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cluster_event_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cluster_event_proto_goTypes,
		DependencyIndexes: file_proto_cluster_event_proto_depIdxs,
		EnumInfos:         file_proto_cluster_event_proto_enumTypes,
		MessageInfos:      file_proto_cluster_event_proto_msgTypes,
	}.Build()
	File_proto_cluster_event_proto = out.File
	file_proto_cluster_event_proto_rawDesc = nil
	file_proto_cluster_event_proto_goTypes = nil
	file_proto_cluster_event_proto_depIdxs = nil
}
