// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: proto/exec-ins/proto.proto

package execinspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event_Type int32

const (
	Event_ROUTINE_SUBMIT Event_Type = 0
	Event_GET_WAIT       Event_Type = 1
	Event_EXIT           Event_Type = 2
	Event_INIT           Event_Type = 3
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0: "ROUTINE_SUBMIT",
		1: "GET_WAIT",
		2: "EXIT",
		3: "INIT",
	}
	Event_Type_value = map[string]int32{
		"ROUTINE_SUBMIT": 0,
		"GET_WAIT":       1,
		"EXIT":           2,
		"INIT":           3,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_exec_ins_proto_proto_enumTypes[0].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_proto_exec_ins_proto_proto_enumTypes[0]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_exec_ins_proto_proto_rawDescGZIP(), []int{1, 0}
}

type Event_Status int32

const (
	Event_SUCC Event_Status = 0
	Event_FAIL Event_Status = 1
)

// Enum value maps for Event_Status.
var (
	Event_Status_name = map[int32]string{
		0: "SUCC",
		1: "FAIL",
	}
	Event_Status_value = map[string]int32{
		"SUCC": 0,
		"FAIL": 1,
	}
)

func (x Event_Status) Enum() *Event_Status {
	p := new(Event_Status)
	*p = x
	return p
}

func (x Event_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_exec_ins_proto_proto_enumTypes[1].Descriptor()
}

func (Event_Status) Type() protoreflect.EnumType {
	return &file_proto_exec_ins_proto_proto_enumTypes[1]
}

func (x Event_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Status.Descriptor instead.
func (Event_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_exec_ins_proto_proto_rawDescGZIP(), []int{1, 1}
}

type Routine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FnName string `protobuf:"bytes,2,opt,name=fn_name,json=fnName,proto3" json:"fn_name,omitempty"`
	Args   []byte `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *Routine) Reset() {
	*x = Routine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_exec_ins_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Routine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routine) ProtoMessage() {}

func (x *Routine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_ins_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routine.ProtoReflect.Descriptor instead.
func (*Routine) Descriptor() ([]byte, []int) {
	return file_proto_exec_ins_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Routine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Routine) GetFnName() string {
	if x != nil {
		return x.FnName
	}
	return ""
}

func (x *Routine) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     Event_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=execins.Event_Type" json:"type,omitempty"`
	WithData *bool         `protobuf:"varint,2,opt,name=with_data,json=withData,proto3,oneof" json:"with_data,omitempty"`
	RefIds   []string      `protobuf:"bytes,3,rep,name=ref_ids,json=refIds,proto3" json:"ref_ids,omitempty"`
	Status   *Event_Status `protobuf:"varint,4,opt,name=status,proto3,enum=execins.Event_Status,oneof" json:"status,omitempty"`
	Result   []byte        `protobuf:"bytes,5,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Error    *string       `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Routine  *Routine      `protobuf:"bytes,7,opt,name=routine,proto3,oneof" json:"routine,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_exec_ins_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_ins_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_exec_ins_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_ROUTINE_SUBMIT
}

func (x *Event) GetWithData() bool {
	if x != nil && x.WithData != nil {
		return *x.WithData
	}
	return false
}

func (x *Event) GetRefIds() []string {
	if x != nil {
		return x.RefIds
	}
	return nil
}

func (x *Event) GetStatus() Event_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Event_SUCC
}

func (x *Event) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Event) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

var File_proto_exec_ins_proto_proto protoreflect.FileDescriptor

var file_proto_exec_ins_proto_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x2d, 0x69, 0x6e, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78,
	0x65, 0x63, 0x69, 0x6e, 0x73, 0x22, 0x46, 0x0a, 0x07, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x66, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x9e, 0x03,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x69, 0x6e, 0x73, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x66, 0x49, 0x64, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x65, 0x78,
	0x65, 0x63, 0x69, 0x6e, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x69,
	0x6e, 0x73, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x48, 0x04, 0x52, 0x07, 0x72, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x22, 0x3c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x0e, 0x52, 0x4f, 0x55, 0x54, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x4d,
	0x49, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x45, 0x54, 0x5f, 0x57, 0x41, 0x49, 0x54,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x58, 0x49, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x4e, 0x49, 0x54, 0x10, 0x03, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x08, 0x0a, 0x04, 0x53, 0x55, 0x43, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41,
	0x49, 0x4c, 0x10, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x61,
	0x6e, 0x7a, 0x73, 0x2f, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65,
	0x78, 0x65, 0x63, 0x69, 0x6e, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_exec_ins_proto_proto_rawDescOnce sync.Once
	file_proto_exec_ins_proto_proto_rawDescData = file_proto_exec_ins_proto_proto_rawDesc
)

func file_proto_exec_ins_proto_proto_rawDescGZIP() []byte {
	file_proto_exec_ins_proto_proto_rawDescOnce.Do(func() {
		file_proto_exec_ins_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_exec_ins_proto_proto_rawDescData)
	})
	return file_proto_exec_ins_proto_proto_rawDescData
}

var file_proto_exec_ins_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_exec_ins_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exec_ins_proto_proto_goTypes = []interface{}{
	(Event_Type)(0),   // 0: execins.Event.Type
	(Event_Status)(0), // 1: execins.Event.Status
	(*Routine)(nil),   // 2: execins.Routine
	(*Event)(nil),     // 3: execins.Event
}
var file_proto_exec_ins_proto_proto_depIdxs = []int32{
	0, // 0: execins.Event.type:type_name -> execins.Event.Type
	1, // 1: execins.Event.status:type_name -> execins.Event.Status
	2, // 2: execins.Event.routine:type_name -> execins.Routine
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_exec_ins_proto_proto_init() }
func file_proto_exec_ins_proto_proto_init() {
	if File_proto_exec_ins_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_exec_ins_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Routine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_exec_ins_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_exec_ins_proto_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_exec_ins_proto_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_exec_ins_proto_proto_goTypes,
		DependencyIndexes: file_proto_exec_ins_proto_proto_depIdxs,
		EnumInfos:         file_proto_exec_ins_proto_proto_enumTypes,
		MessageInfos:      file_proto_exec_ins_proto_proto_msgTypes,
	}.Build()
	File_proto_exec_ins_proto_proto = out.File
	file_proto_exec_ins_proto_proto_rawDesc = nil
	file_proto_exec_ins_proto_proto_goTypes = nil
	file_proto_exec_ins_proto_proto_depIdxs = nil
}
